version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: docs
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: docs

	docs:
		build: .
		image: chamaconekt/docs
		links:
		- postgres
		container_name: docs
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- docs
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/docs-nginx/nginx.conf
		depends_on:
			- docs
		ports:
			- 80:80
		volumes_from:
			- docs

volumes:
	docs-static-files:
		driver:local